yaml format on `backend-style.yaml`

diff --git a/.github/workflows/backend-style.yaml b/.github/workflows/backend-style.yaml
--- a/.github/workflows/backend-style.yaml
+++ b/.github/workflows/backend-style.yaml
@@ -10,7 +10,9 @@ on:
     # branches: [ "main" ]
     # tags: [ "*.*.*" ]
     paths:
-      - 'backend/**'
+      - "backend/**"
+      - ".github/workflows/**"
+      - "!frontend/**"
 
 jobs:
   build:
@@ -20,19 +22,19 @@ jobs:
 
     runs-on: ${{ matrix.os }}
     steps:
-    - name: 📥 Checkout repository
-      uses: actions/checkout@v1
+      - name: 📥 Checkout repository
+        uses: actions/checkout@v1
 
-    - name: ✍  Check hlint and stylish
-      run: |
-        curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .
-        curl -sSL https://raw.github.com/jaspervdj/stylish-haskell/master/scripts/latest.sh | sh -s $(find . -type f -name "*.hs" ! -path "*.stack-work*") -i
-        if [ -z "$(git status --porcelain)" ]; then
-            echo "No style errors detected."
-        else
-            echo "Style errors detected:"
-            git --no-pager diff
-            exit 1
-        fi
-      # https://stackoverflow.com/questions/57806624/github-actions-how-to-build-project-in-sub-directory
-      working-directory: backend
+      - name: ✍  Check hlint and stylish
+        run: |
+          curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .
+          curl -sSL https://raw.github.com/jaspervdj/stylish-haskell/master/scripts/latest.sh | sh -s $(find . -type f -name "*.hs" ! -path "*.stack-work*") -i
+          if [ -z "$(git status --porcelain)" ]; then
+              echo "No style errors detected."
+          else
+              echo "Style errors detected:"
+              git --no-pager diff
+              exit 1
+          fi
+        # https://stackoverflow.com/questions/57806624/github-actions-how-to-build-project-in-sub-directory
+        working-directory: backend
